name: 'ecommerce_revenue_operations'
version: '1.0.0'

profile: 'ecommerce_revenue_operations'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_revenue_operations:
    staging:
      +materialized: view

    intermediate:
      +materialized: view
