-- ============================================================
-- E-COMMERCE REVENUE & OPERATIONS ANALYTICS
-- Snowflake environment setup
-- ============================================================

CREATE WAREHOUSE IF NOT EXISTS ECOMMERCE_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS ECOMMERCE_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS ECOMMERCE_ANALYTICS.RAW;

CREATE SCHEMA IF NOT EXISTS ECOMMERCE_ANALYTICS.ANALYTICS;

USE WAREHOUSE ECOMMERCE_WH;
USE DATABASE ECOMMERCE_ANALYTICS;
USE SCHEMA RAW;

SHOW WAREHOUSES LIKE 'ECOMMERCE_WH';
SHOW SCHEMAS IN DATABASE ECOMMERCE_ANALYTICS;
